backend:
  name: git-gateway
  branch: master
media_folder: public/media
public_folder: media
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
  - name: "work"
    label: "Work"
    files:
      - label: "Motion"
        name: "motion"
        file: "content/work/motion.md"
        fields:
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - label: "Projects"
            name: "projects"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
              - { label: "Video", name: "video", widget: "file" }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                }
