backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: public/media
public_folder: media
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "layout"
        label: "Layout"
        file: "content/layout.yml"
        delete: false
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {
                  label: "Base Logo Image",
                  name: "baseLogo",
                  widget: "image",
                  comment: "The base logo image to use on all pages except the homepage",
                }
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {
                  label: "Footer Text",
                  name: "textContent",
                  widget: "markdown",
                }
      - label: "Home"
        name: "home"
        file: "content/home.yml"
        delete: false
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Page Title", name: "pageTitle", widget: "string" }
              - {
                  label: "Page Description",
                  name: "pageDescription",
                  widget: "string",
                }
              - {
                  label: "OpenGraph Preview Image",
                  name: "ogImage",
                  widget: "image",
                }
          - { label: "Home Header Logo", name: "logoImage", widget: "image" }
          - { label: "Reel Video File", name: "reel", widget: "file" }
          - label: "About Section"
            name: "aboutSection"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
              - {
                  label: "Section Background Image",
                  name: "backgroundImage",
                  widget: "image",
                }
              - { label: "Resume File", name: "resumeFile", widget: "file" }
          - label: "Contact Section"
            name: "contactSection"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work Pages"
    label_singular: "Work Page"
    folder: "content/work"
    format: "yml"
    identifier_field: "slug"
    create: true
    fields:
      - {
          label: "Link Text",
          name: "linkText",
          widget: "string",
          hint: "The text to use in links to this work page",
        }
      - {
          label: "URL Slug",
          name: "slug",
          widget: "string",
          hint: "The URL slug (ie, jessicakeoshian.com/work/{slug}) to represent where this work page should live on the site",
          pattern:
            [
              "^[a-z0-9-_]+$",
              "Slugs may only use lowercase letters (a-z), numbers (0-9), underscores (_), and dashes (-)",
            ],
        }
      - {
          label: "List Order",
          name: "order",
          widget: "number",
          default: 1,
          min: 1,
          value_type: "int",
        }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - {
              label: "Page Description",
              name: "pageDescription",
              widget: "string",
            }
          - {
              label: "OpenGraph Preview Image",
              name: "ogImage",
              widget: "image",
            }
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Subheading", name: "subHeading", widget: "string" }
      - label: "Content Rows"
        name: "contentRows"
        widget: list
        fields:
          - label: "Number of Columns"
            name: "columnCount"
            widget: "number"
            default: 1
            min: 1
            hint: "The number of columns that this row should be divided into"
          - label: "Contents"
            name: "contents"
            widget: "list"
            min: 1
            fields:
              - {
                  label: "Content Type",
                  name: "type",
                  widget: "select",
                  options: ["copy", "image", "video", "audio"],
                  default: "copy",
                }
              - {
                  label: "Text Contents",
                  name: "text",
                  widget: "markdown",
                  required: false,
                }
              - {
                  label: "Text Alignment",
                  name: "textAlignment",
                  widget: "select",
                  options: ["left", "center", "right"],
                  default: "left",
                  required: false,
                }
              - {
                  label: "Image File",
                  name: "imageFile",
                  widget: "image",
                  required: false,
                }
              - {
                  label: "Video File",
                  name: "videoFile",
                  widget: "file",
                  required: false,
                }
              - {
                  label: "Audio File",
                  name: "audioFile",
                  widget: "file",
                  required: false,
                }
              - {
                  label: "Column Width",
                  name: "columnWidth",
                  hint: "The number of columns in the row that this content should fill",
                  widget: "number",
                  default: 1,
                }
