backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: public/media
public_folder: media
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "layout"
        label: "Layout"
        file: "content/layout.yml"
        delete: false
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {
                  label: "Base Logo Image",
                  name: "baseLogo",
                  widget: "image",
                  comment: "The base logo image to use on all pages except the homepage",
                }
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {
                  label: "Footer Text",
                  name: "textContent",
                  widget: "markdown",
                }
      - label: "Home"
        name: "home"
        file: "content/home.yml"
        delete: false
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Page Title", name: "pageTitle", widget: "string" }
              - {
                  label: "Page Description",
                  name: "pageDescription",
                  widget: "string",
                }
              - {
                  label: "OpenGraph Preview Image",
                  name: "ogImage",
                  widget: "image",
                }
          - { label: "Home Header Logo", name: "logoImage", widget: "image" }
          - { label: "Reel Video File", name: "reel", widget: "file" }
          - label: "About Section"
            name: "aboutSection"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
              - {
                  label: "Section Background Image",
                  name: "backgroundImage",
                  widget: "image",
                }
              - { label: "Resume File", name: "resumeFile", widget: "file" }
          - label: "Contact Section"
            name: "contactSection"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work"
    files:
      - label: "Motion"
        name: "motion"
        file: "content/work/motion.yml"
        delete: false
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Page Title", name: "pageTitle", widget: "string" }
              - {
                  label: "Page Description",
                  name: "pageDescription",
                  widget: "string",
                }
              - {
                  label: "OpenGraph Preview Image",
                  name: "ogImage",
                  widget: "image",
                }
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - {
              label: "Page Description",
              name: "pageDescription",
              widget: "markdown",
            }
          - label: "Projects"
            name: "projects"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
              - { label: "Video", name: "video", widget: "file" }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                }
