backend:
  name: git-gateway
  branch: master
media_folder: public/media
public_folder: media
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - { label: "Reel Video File", name: "reel", widget: "file" }
          - {
              label: "About Section Contents",
              name: "about",
              widget: "markdown",
            }
          - {
              label: "Contact Section Contents",
              name: "contact",
              widget: "markdown",
            }
  - name: "work"
    label: "Work"
    files:
      - label: "Motion"
        name: "motion"
        file: "content/work/motion.md"
        fields:
          - { label: "Page Title", name: "pageTitle", widget: "string" }
          - label: "Projects"
            name: "projects"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
              - { label: "Video", name: "video", widget: "file" }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                }
